config/routes.rb
Rails.application.routes.draw do

  root 'garages#new'

  resources :garages, only: [:new, :create, :show]
  post 'parking_vehicle', to: 'garages#park_vehicle'
  post 'find_vehicle', to: 'garages#find_vehicle'
end

app/models/car.rb
class Car < Vehicle

end

app/models/garage.rb
class Garage < ActiveRecord::Base
  has_many :vehicles
  has_many :levels
  has_many :lots

  validates_presence_of :number_levels, :number_lots

  def number_of_parking_places
    self.number_levels * self.number_lots
  end

  def create_new_level?
    self.vehicles.count / ( self.number_lots * self.levels.count ) >= 1 and self.levels.count < self.number_levels ? true : false
  end

  def delete_level?
    self.vehicles.count % self.number_lots == 0 ? true : false 
  end  

  def has_empty_lot?
    ( self.number_lots * self.number_levels ) - self.vehicles.count > 0 ? true : false  
  end

  def number_of_empty_lots
    ( self.number_lots * self.number_levels ) - self.vehicles.count
  end
end

app/models/level.rb
class Level < ActiveRecord::Base
  belongs_to :garage
  has_many :lots
  has_many :vehicles
end

app/models/lot.rb
class Lot < ActiveRecord::Base
  belongs_to :garage
  belongs_to :level
  belongs_to :vehicle
end

app/models/motorbike.rb
class Motorbike < Vehicle

end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  belongs_to :lot
  belongs_to :level
  belongs_to :garage

  validates_presence_of :plate
  validates_uniqueness_of :plate
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/garages_controller.rb
class GaragesController < ApplicationController
  
  def show
    @garage = Garage.find(params[:id])
  end

  def new
    @garage = Garage.new
  end

  def create
    @garage = Garage.new(garage_params)

    if @garage.save 
      @garage.levels.create(number: 1)
      redirect_to garage_path(@garage.id)
    else
      flash[:error] = "The garage could not be created because of: #{ @garage.errors.full_messages }"
      render :new
    end
  end

  def park_vehicle     
    @garage = Garage.find(params[:garage_id])

    if params[:park_button]
      if @garage.has_empty_lot?        
        @vehicle = new_vehicle_of_type

        if @vehicle.save 
          set_level_and_lot @garage, @vehicle
        else
          flash[:error] = "Vehicle cannot be parked because: #{ @vehicle.errors.full_messages }" 
        end

      else
        flash[:error] = "There is no room for this vehicle. Sorry." 
      end

    elsif params[:unpark_button]
      unpark_vehicle params, @garage
    end
      
    redirect_to garage_path @garage.id   
  end  

  def find_vehicle
    @garage = Garage.find(params[:garage_id])
    @vehicle = Vehicle.find_by(plate: params[:plate])
    
    if @vehicle
      flash[:notice] = "The vehicle with plate #{ @vehicle.plate }, is in level: #{ @vehicle.level.number }, lot: #{ @vehicle.lot.number }"
    else
      flash[:error] = "There is no vehicle in this garage with the submited plate: #{ params[:plate] }"
    end  

    redirect_to garage_path @garage.id  

  end

  private

  def garage_params
    params.require(:garage).permit(:number_levels, :number_lots)
  end

  def new_vehicle_of_type
    if params[:type] == "car"
      Car.new(plate: params[:plate])
    else
      Motorbike.new(plate: params[:plate])
    end    
  end

  def set_level_and_lot garage, vehicle

    if garage.create_new_level?
      level_number = garage.levels.last.number + 1
      garage.levels.create(number: level_number)
    end

    if garage.lots.count == 0
      lot = Lot.create(garage_id: garage.id, vehicle_id: vehicle.id, level_id: garage.levels.last.id, number: 1)    
    elsif garage.lots.where(vehicle_id: nil).count > 0
      lot = garage.lots.where(vehicle_id: nil).first
      lot.update_attributes(vehicle_id: vehicle.id)      
    else
      lot =Lot.create(garage_id: garage.id, vehicle_id: vehicle.id, level_id: garage.levels.last.id, number: garage.lots.last.number + 1)
    end
   
    vehicle.update_attributes(garage_id: garage.id, lot_id: lot.id, level_id: garage.levels.last.id)
    
    flash[:error] = "The vehicle has been succesfully parked in level: #{ vehicle.level.number }, lot: #{ vehicle.lot.number }."  
  end

  def unpark_vehicle params, garage
    vehicle = Vehicle.find_by(plate: params[:plate])

    if vehicle
      lot = Lot.find_by(vehicle_id: vehicle.id)
      lot.update_attributes(vehicle_id: nil)

      vehicle.delete

      flash[:notice] = "The #{ params[:type] } with plate: #{ params[:plate] }, has left the garage"
    else
      flash[:error] = "There is no vehicle in this garage with the submited plate: #{ params[:plate] }"
    end               
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/garages/_form.html.erb
<%= form_tag parking_vehicle_path, method: "post" do %>
  <%= hidden_field_tag :garage_id, value: @garage.id %>
  <%= label_tag("License plate") %>
  <br>
  <%= text_field_tag(:plate) %>
  <br>
  <br>
  <%= label_tag("Car") %>
  <br>
  <%= radio_button_tag(:type, "car") %>
  <br>
  <%= label_tag("Motorbyke") %>
  <br>
  <%= radio_button_tag(:type, "motorbyke") %>
  <br>
  <br>

  <%= submit_tag("Park vehicle") %>
  
<% end %>

app/views/garages/new.html.erb
<h4> Please create a new garage typing the number of levels ans lots per level you want.</h4>

<%= form_for @garage do |f| %>
  <%= f.label "Number of levels" %>
  <br>
  <%= f.number_field :number_levels %>
  <br>
  <br>
  <%= f.label "Number of lots per level" %>
  <br>
  <%= f.number_field :number_lots %>
  <br>
  <br>
  <%= f.submit "Create" %>  
<% end %>

app/views/garages/show.html.erb
<br>
<p><h4> Please type the plate of the vehicle and the button with the option you want.</h4></p>
<%= form_tag parking_vehicle_path, method: "post" do %>

  <%= hidden_field_tag :garage_id, @garage.id %>
  <%= label_tag("License plate") %>
  <br>
  <%= text_field_tag(:plate) %>
  <br>
  <br>
  <%= label_tag("Car") %>
  <br>
  <%= radio_button_tag(:type, "car") %>
  <br>
  <%= label_tag("Motorbyke") %>
  <br>
  <%= radio_button_tag(:type, "motorbyke") %>
  <br>
  <br>

  <%= submit_tag("Park vehicle", name: "park_button") %>
  <%= submit_tag("Unpark a vehicle", name: "unpark_button") %>
  
<% end %>


<p>
  <div> 
    <%= "The parking has #{ @garage.vehicles.count } vehicles, parked. There are: #{ @garage.number_of_empty_lots } lots available." 
    %>
  </div>
<p/>

<%= form_tag find_vehicle_path, method: "post" do %>

  <%= hidden_field_tag :garage_id, @garage.id %>
  <%= label_tag("License plate") %>
  <br>
  <%= text_field_tag(:plate) %>
  <br>
  <br>

  <%= submit_tag("Find vehicle") %>
 
<% end %>

<p>
  <%= button_to "Restart", root_path, method: "get", data: { confirm: "Are you sure? It will delele all the data." } %>
<p/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TheGarage</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'shared/messages' %>
<%= yield %>

</body>
</html>

app/views/shared/_messages.html.erb
<% flash.each do |name, msg| %>
    <h3> <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %> </h3>
<% end %>